# Codecov Configuration for Mining Marketplace Backend
# This file configures how Codecov processes coverage reports

coverage:
  # Coverage precision (number of decimal places)
  precision: 2
  
  # Round coverage to nearest integer
  round: down
  
  # Coverage range for color coding
  range: "70...100"
  
  # Status checks configuration
  status:
    # Project-wide coverage requirements
    project:
      default:
        target: 80%
        threshold: 2%
        base: auto
        if_ci_failed: error
    
    # Patch coverage for new code
    patch:
      default:
        target: 75%
        threshold: 5%
        base: auto
        if_ci_failed: error

# Comment configuration for pull requests
comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

# Ignore paths from coverage
ignore:
  - "src/**/*.test.ts"
  - "src/**/*.spec.ts"
  - "src/**/__tests__/**"
  - "src/types/**"
  - "dist/**"
  - "coverage/**"
  - "node_modules/**"
  - "*.config.js"
  - "*.setup.js"

# Flag configuration for different test types
flags:
  backend:
    paths:
      - src/
    carryforward: true
  
  unit-tests:
    paths:
      - src/
    carryforward: true
  
  integration-tests:
    paths:
      - src/
    carryforward: true

# GitHub integration
github_checks:
  annotations: true

